import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "next-auth/react";
import { AppProps } from "next/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <script src="https://kit.fontawesome.com/3a9cf2a124.js" crossOrigin="anonymous"></script>
        <SessionProvider session={session}>
          <main>
            <Component {...pageProps} />
          </main>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
