import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <script src="https://kit.fontawesome.com/3a9cf2a124.js" crossOrigin="anonymous"></script>
        <SessionProvider>
          <main>
            {children}
          </main>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
